name: flowrate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bloodflow.riv

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700

        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
          weight: 700

